### ISSUE TITLE
Days left feature not working

### ISSUE THREAD

**Issue by Zeeshanef** [Cryptolens/SKGL#7]
I implemented days left feature as per the instructions but it doesn't work. i.e. I installed my application in PC and register the application with a key which supposed to expire in 3 days but after 3 days application was still running without asking serial number again. Any idea?

**Comment by artemlos** [comment]
@Zeeshanef It might be 3 days inclusive, i.e. I think it would stop working on day 4.

**Comment by Zeeshanef** [comment]
Nope. It is even working after more than 30 days.
